### ISSUE TITLE
When upgrading a cask that requires password, update stalls

### ISSUE THREAD

**Issue by waynehoover** [zero-sh/zero.sh#16]
When I update a cask that requires a password, like google chrome, the update just stalls.

Also it would be nice to be able to turn off the new feature to update all casks even those who have auto update turned on.

**Comment by msanders** [comment]
Thanks for the report! Both of these are now fixed in version 0.5.0.

**Comment by waynehoover** [comment]
Thank you for the fast turn around! I have really been enjoying using zero-sh.

**Comment by joelash** [comment]
I'm still experiencing this problem but when installing a new cask. I usually have to ctrl-c and do a `brew reinstall <cask>` to get it actually install.

**Comment by natecox** [comment]
I'm experiencing this issue today, while setting up a new laptop. Any install asking for a password is hanging, and I need to `ctrl+c` and reinstall manually.
